name: 'C++ CI/CD IP adress filtration'

on:
  push:
    branches: ["main1"]

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            asset_postfix: -Linux.deb
            asset_content_type: application/vnd.debian.binary-package
            testing_command: cmake --build . --target test
          - os: windows-latest
            asset_postfix: -win64.deb
            asset_content_type: application/vnd.microsoft.binary-package
            testing_command: ctest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: cmake . -DPATCH_VERSION=${{ github.run_number }} -DWITH_GTEST=ON
      - run: cmake --build .
      - run: ${{ matrix.testing_command }}
      - run: cmake --build . --target package
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v0.0.${{ github.run_number }}
          name: Release v0.0.${{ github.run_number }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run:
          gh release upload v0.0.${{ github.run_number }} ip_sort-0.0.${{ github.run_number }}${{ matrix.asset_postfix }}
